"""add score rules

Revision ID: 1590fcdf9ac1
Revises: 3e7a273bf376
Create Date: 2026-02-09 02:34:24.487415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1590fcdf9ac1'
down_revision = '3e7a273bf376'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score_rules', schema=None) as batch_op:
        batch_op.alter_column('monthly_limit',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('warning_pct',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('uq_score_rule_user_category'), type_='unique')
        batch_op.create_index(batch_op.f('ix_score_rules_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_score_rules_user_id'), ['user_id'], unique=False)
        batch_op.create_unique_constraint('uq_score_rules_user_category', ['user_id', 'category_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score_rules', schema=None) as batch_op:
        batch_op.drop_constraint('uq_score_rules_user_category', type_='unique')
        batch_op.drop_index(batch_op.f('ix_score_rules_user_id'))
        batch_op.drop_index(batch_op.f('ix_score_rules_category_id'))
        batch_op.create_unique_constraint(batch_op.f('uq_score_rule_user_category'), ['user_id', 'category_id'])
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('warning_pct',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=False)
        batch_op.alter_column('monthly_limit',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)

    # ### end Alembic commands ###
